spring.application.name=UberReviewService

spring.datasource.url = jdbc:mysql://localhost:3306/Uber_db_local
spring.datasource.username=root
spring.datasource.password=dhayanoo@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
